# -*- coding: utf-8 -*-,
phrases = ["Que Isso Bixo,ó u Cara lá ó",
"Vamos ver as vídeos casetadas",
"Voltamos já com vídeos Casetadas",
"Abrindo o saco de risadas!",
"Olha só o que faz a maldita manguaça bicho!",
"ERRRROOOOOOOOOUUUUUUUU!!!!",
"E agora,pra desligar essa merda aí,meu. Porra ligou,agora desliga!!! Tá pegando fogo bixo!!",
"Está fera ai bixo",
"Olha o tamanho da Criança",
"Essa fera bicho, às oito e sete",
"Amassando o curió. Hmmmmmm! Mulher ri porque não sabe o que dói",
"Parece uma lagartixa com cólica renal",
"Um exemplo de cidadão brasileiro!",
"Ô loco meu!",
"Puuuuuuuuuuutsss!!",
"Logo após os reclames do Plim-Plim...",
"O looooooooooco meu!",
"E agora, mais do que nunca...",
"Ééé galeraaaaaaaaa",
"A Fininvest dá, por isso todos gostamos dela...",
"Olha aí o japinha.... Ô LOCO MEU!",
"Pooooorra meu, é o maior coral do Brasil!",
"Caindo de cabeça no rrrio!",
"Essa aí dançou...",
"É brincadera bicho.",
"Se vira nos 30!",
"Quem sabe faz ao vivo!",
"E agora as mais loucas vídeo cassetadas, oferecimento da Fininvest.",
"Ta aí galera, você curtiu as vídeos casetadas com um oferecimento da Fininvest.",
"E a partir desse momento galera, mais do que nunca... você vai curtir...",
"Grande Fulano!",
"Fulano é um monstro sagrado da teledramaturgia brasileira.",
"Fulano pra chegar onde chegou...",
"...tanto no pessoal como no profissional.",
"Essa ferinha aqui da música brasileira/do esporte...",
"Enquanto você não encontra a mulher da sua vida, vai se divertindo com as outras.",
"Vem aí o glorioso",
"Orra isso é que é tomar no olho"]

receivers = ["@joao.silva",
			 "#channel",
			 "PLACE YOUR CONTACT LIST HERE"]

web_url = 'PLACE YOUR DEFAULT WEBHOOK HERE'
